import { readFileSync, writeFileSync, mkdirSync } from "node:fs";
import path from "node:path";
import type { NextConfig } from "next";

// /bookmarklet needs extension/extractor.js's source embedded into the
// generated bookmarklet. It used to read that file off disk at request
// time, which worked in local dev but broke in production: this app
// deploys to Cloudflare Workers via OpenNext (see wrangler.jsonc), and
// Workers have no filesystem at runtime at all — fs.readFileSync there
// isn't a missing-file problem, it's not supported, full stop.
//
// Fix: read the file once here, at config-evaluation time (this file is
// loaded by the Next CLI for every `next dev`/`next build`, on any
// platform, well before anything is deployed), and write it out as a
// plain TS module the app can import normally. That module gets bundled
// like any other source file, so it works the same on Cloudflare, Vercel,
// or anywhere else.
function generateExtractorSourceModule() {
  const extractorPath = path.join(process.cwd(), "extension", "extractor.js");
  const source = readFileSync(extractorPath, "utf8");

  const outDir = path.join(process.cwd(), "src", "generated");
  mkdirSync(outDir, { recursive: true });
  writeFileSync(
    path.join(outDir, "extractorSource.ts"),
    `// Auto-generated by next.config.ts from extension/extractor.js — do not edit directly.\nexport const EXTRACTOR_SOURCE = ${JSON.stringify(source)};\n`
  );
}

generateExtractorSourceModule();

const nextConfig: NextConfig = {};

export default nextConfig;
